# Generated by Django 3.0.2 on 2020-01-17 11:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('transno', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('nbids', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transno', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transno', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'From Produce'), ('2', 'From Warehouse'), ('3', 'From both')], max_length=1)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
