# Generated by Django 3.0.2 on 2020-01-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Produce'),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Warehouse'),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Produce'),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Warehouse'),
        ),
        migrations.AddField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produce',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='user.Location'),
        ),
        migrations.AddField(
            model_name='produce',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='user.FoodGrain'),
        ),
        migrations.AddField(
            model_name='placebid',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Bid'),
        ),
        migrations.AddField(
            model_name='placebid',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FoodGrain'),
        ),
    ]
